"""Spark-side FT runner: axolotl YAML emitter + GPU-aware launcher.

Runs on Spark DGX GB10 (ARM64 + CUDA 13). Pre-checks GPU memory before
launching. Uses the venv_cu130 environment per ~/.claude/CLAUDE.md
"Technical defaults".

Workflow:
1. Receive train.jsonl + val.jsonl + base_model_id (e.g. "Qwen/Qwen3-8B")
2. Emit axolotl_config.yaml with LoRA defaults sized for GB10's 121GB mem ceiling
3. Run nvidia-smi to verify ≥40% free VRAM before launching
4. Launch via subprocess; capture logs
5. On completion: convert LoRA → GGUF for Ollama compat
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path
from textwrap import dedent

logger = logging.getLogger(__name__)


def gpu_free_mb() -> int:
    """Return free VRAM in MB on first GPU. Returns 0 if nvidia-smi unavailable."""
    if shutil.which("nvidia-smi") is None:
        return 0
    try:
        out = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=memory.free", "--format=csv,noheader,nounits"],
            text=True,
            timeout=5,
        )
        return int(out.splitlines()[0].strip())
    except Exception as e:
        logger.warning("nvidia-smi failed: %s", e)
        return 0


def emit_axolotl_config(
    *,
    base_model: str,
    train_jsonl: Path,
    val_jsonl: Path,
    output_dir: Path,
    max_seq_len: int = 2048,
    lora_r: int = 16,
    lora_alpha: int = 32,
    learning_rate: float = 2e-4,
    epochs: int = 3,
    batch_size: int = 4,
    gradient_accumulation_steps: int = 4,
) -> Path:
    """Write an axolotl YAML tuned for Spark GB10 (121GB unified mem ceiling).

    Sized per ~/.claude/CLAUDE.md "Spark 121GB ceiling: max_seq_len 2048,
    lora_r 32 max for DPO" — using 16 here as a safe default for SFT.
    """
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    cfg_path = output_dir / "axolotl_config.yaml"
    cfg = dedent(f"""\
        # axolotl SFT config — Spark GB10, ARM64 + CUDA 13
        # Generated by slancha-train. Tune via env vars in spark_runner.py.

        base_model: {base_model}
        model_type: AutoModelForCausalLM
        tokenizer_type: AutoTokenizer

        load_in_4bit: false
        strict: false

        datasets:
          - path: {train_jsonl.resolve()}
            type: chat_template
            chat_template: chatml
            field_messages: messages
            split: train
          - path: {val_jsonl.resolve()}
            type: chat_template
            chat_template: chatml
            field_messages: messages
            split: validation

        dataset_prepared_path: {output_dir / "prepared"}
        output_dir: {output_dir / "out"}

        sequence_len: {max_seq_len}
        sample_packing: true
        pad_to_sequence_len: true

        adapter: lora
        lora_r: {lora_r}
        lora_alpha: {lora_alpha}
        lora_dropout: 0.05
        lora_target_linear: true

        gradient_accumulation_steps: {gradient_accumulation_steps}
        micro_batch_size: {batch_size}
        num_epochs: {epochs}
        optimizer: adamw_torch_fused
        lr_scheduler: cosine
        learning_rate: {learning_rate}

        bf16: auto
        flash_attention: false  # GB10 (sm_120) — flash-attn not always pre-built; check
        gradient_checkpointing: true
        warmup_ratio: 0.05
        weight_decay: 0.0

        eval_steps: 50
        save_steps: 100
        save_total_limit: 3

        logging_steps: 10
        ddp_find_unused_parameters: false

        wandb_project: slancha-train
        # WANDB_DISABLED=true via env to skip
    """)
    cfg_path.write_text(cfg)
    return cfg_path


def precheck_gpu(min_free_mb: int = 40_000) -> tuple[bool, str]:
    """Return (ok, message). Bails if GPU has too little free memory for safe FT."""
    free = gpu_free_mb()
    if free == 0:
        return False, "nvidia-smi unavailable; aborting (set --skip-precheck to override)"
    if free < min_free_mb:
        return False, f"only {free}MB free on GPU; need ≥{min_free_mb}MB. Other workloads running?"
    return True, f"GPU OK: {free}MB free"


def launch_axolotl(
    cfg_path: Path,
    *,
    venv_path: Path = Path("/home/admin/venv_cu130"),
    extra_env: dict[str, str] | None = None,
) -> int:
    """Launch axolotl train. Returns subprocess exit code.

    Caller is responsible for already having activated the right env (or
    venv_path is set correctly). Streams stdout/stderr to caller's tty.
    """
    import os

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"
    env["WANDB_DISABLED"] = env.get("WANDB_DISABLED", "true")
    if extra_env:
        env.update(extra_env)

    python = venv_path / "bin" / "python"
    cmd = [
        str(python),
        "-m",
        "axolotl.cli.train",
        str(cfg_path),
    ]
    logger.info("launching: %s", " ".join(cmd))
    return subprocess.call(cmd, env=env)
